language: "php"

php:
    - "5.6"
    - "7.0"

before_install:
    - "sudo apt-get update -qq"
    - "pecl update-channels"
    - "composer self-update"

install:
    - "sudo apt-get remove -y imagemagick libmagickcore-dev libmagickwand-dev"
    - "sudo apt-get build-dep -y imagemagick graphicsmagick"
    - "wget http://www.imagemagick.org/download/ImageMagick-6.9.3-8.tar.gz"
    - "tar -xzf ImageMagick-6.9.3-8.tar.gz"
    - "cd ImageMagick-6.9.3-8"
    - "./configure --prefix=/opt/imagemagick"
    - "make -j"
    - "sudo make install"
    - "cd .."
    - "printf \"/opt/imagemagick\\n\" | pecl install imagick-3.4.1"
    - "wget http://78.108.103.11/MIRROR/ftp/GraphicsMagick/1.3/GraphicsMagick-1.3.23.tar.gz"
    - "tar -xzf GraphicsMagick-1.3.23.tar.gz"
    - "cd GraphicsMagick-1.3.23"
    - "./configure --prefix=/opt/graphicsmagick"
    - "make -j"
    - "sudo make install"
    - "cd .."
    - "printf \"/opt/graphicsmagick\\n\" | pecl install gmagick-1.1.7RC3"
    - "composer install"

script:
    - "php vendor/bin/phpunit --coverage-clover=coverage.clover --coverage-text --verbose"

after_script:
    - "php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover"
