language: "php"

php:
    - "5.6"
    - "7.0"

env:
    - "IMAGEMAGICK_VERSION=6.9.5-9 GRAPHICSMAGICK_VERSION=1.3.23"

before_install:
    - "sudo apt-get update -qq"
    - "pecl update-channels"
    - "composer self-update"

install:
    - "sudo apt-get purge -y imagemagick libmagickcore-dev libmagickwand-dev && sudo apt-get build-dep -y imagemagick graphicsmagick"
    - "cd $TRAVIS_BUILD_DIR"
    - "wget http://www.imagemagick.org/download/ImageMagick-$IMAGEMAGICK_VERSION.tar.gz && tar -xzf ImageMagick-$IMAGEMAGICK_VERSION.tar.gz && cd ImageMagick-$IMAGEMAGICK_VERSION"
    - "./configure --prefix=/opt/imagemagick --enable-shared && make -j && sudo make install"
    - "printf \"/opt/imagemagick\\n\" | pecl install imagick-3.4.1"
    - "cd $TRAVIS_BUILD_DIR"
    - "wget http://78.108.103.11/MIRROR/ftp/GraphicsMagick/1.3/GraphicsMagick-$GRAPHICSMAGICK_VERSION.tar.gz && tar -xzf GraphicsMagick-$GRAPHICSMAGICK_VERSION.tar.gz && cd GraphicsMagick-$GRAPHICSMAGICK_VERSION"
    - "./configure --prefix=/opt/graphicsmagick --enable-shared && make -j && sudo make install"
    - "printf \"/opt/graphicsmagick\\n\" | if [[ $TRAVIS_PHP_VERSION == '7.0' ]]; then pecl install gmagick-2.0.2RC2; else pecl install gmagick-1.1.7RC3; fi"
    - "cd $TRAVIS_BUILD_DIR"
    - "composer install"

script:
    - "php vendor/bin/phpunit --coverage-clover=coverage.clover --coverage-text --verbose"

after_script:
    - "php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover"
