language: "php"

php:
    - "5.6"
    - "7.0"

before_install:
    - "sudo apt-get update -qq"
    - "pecl update-channels"
    - "composer self-update"

install:
    - "sudo apt-get install -y imagemagick graphicsmagick"
    - "printf \"\\n\" | pecl install imagick"
    - "printf \"\\n\" | pecl install gmagick-1.1.7RC3"
    - "composer install"

script:
    - "php vendor/bin/phpunit --coverage-clover=coverage.clover --coverage-text --verbose"

after_script:
    - "php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover"
